<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlogManagement.Application.Contracts\BlogManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\BlogManagment.Domain\BlogManagment.Domain.csproj" />
  </ItemGroup>

</Project>
