<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CM.Domain\CM.Domain.csproj" />
    <ProjectReference Include="..\cm.infra.EfCore\CM.Infra.EfCore.csproj" />
    <ProjectReference Include="..\CommentManagement.Application\CommentManagement.Application.csproj" />
  </ItemGroup>

</Project>
