<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlogManagement.Infrastructure.Configuration\BlogManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\CM.Infra.Bootstrapper\CM.Infra.Bootstrapper.csproj" />
    <ProjectReference Include="..\DiscountManagement.Configuration\DiscountManagement.Configuration.csproj" />
    <ProjectReference Include="..\InventoryManagement.Infrastructure.Configuration\InventoryManagement.Infrastructure.Configuration.csproj" />
    <ProjectReference Include="..\ShopManagement.Configuration\ShopManagement.Configuration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Shared\Components\Slide\" />
    <Folder Include="wwwroot\ProductPictures\" />
  </ItemGroup>
	

	
</Project>
